SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `mailing_list`;
DROP TABLE IF EXISTS `subscriber`;
DROP TABLE IF EXISTS `email`;
DROP TABLE IF EXISTS `email_log`;
SET GLOBAL FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS `user` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(255) NOT NULL,
	`last_name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`username` VARCHAR(355) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`created` DATE NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `mailing_list` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`list_name` VARCHAR(255) NOT NULL,
	`created` DATE NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `subscriber` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(255) NOT NULL,
	`last_name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(355) NOT NULL,
	`created` DATE NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `subscriber_mailing_list` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`subscriber_id` INT(11) UNSIGNED NOT NULL,
	`mail_list_id` INT(11) UNSIGNED NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`created` DATE NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	CONSTRAINT FK_subscriber_mailing_list_subscriberid FOREIGN KEY (subscriber_id) REFERENCES `subscriber`(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_subscriber_mailing_list_maillistid FOREIGN KEY (mail_list_id) REFERENCES `mailing_list`(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  `email` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`mailgun_id` VARCHAR(255)NOT NULL,
	`mail_list_id` INT(11) UNSIGNED NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `body` TEXT NOT NULL,
  `created` DATE NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `email_log` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`email_id` INT(11) UNSIGNED NOT NULL,
	`subscriber_id` INT(11) UNSIGNED NOT NULL,
	`status` INT(11) UNSIGNED NOT NULL,
	`created` DATE NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	CONSTRAINT FK_email_log_emailid FOREIGN KEY (email_id) REFERENCES `email`(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_email_log_subscriberid FOREIGN KEY (subscriber_id) REFERENCES `subscriber`(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  `email_status` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NOT NULL,
  `created` DATE NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

INSERT INTO `email_status` (`status`, `created`) VALUES ('Sent', NOW()), ('Delivered', NOW()), ('Read', NOW()), ('Failed', NOW());
